export const QUESTIONS_REQUEST = 'QUESTIONS_REQUEST';
export const QUESTIONS_SUCCESS = 'QUESTIONS_SUCCESS';
export const QUESTIONS_FAILURE = 'QUESTIONS_FAILURE';
export const UPDATE_NEW_QUESTION = 'UPDATE_NEW_QUESTION';
