const SIGNUP = {
    CREATE_ACCOUNT: 'CREATE_ACCOUNT',
    CREATE_ACCOUNT_SUCCESS: 'CREATE_ACCOUNT_SUCCESS',
    CREATE_ACCOUNT_ERROR: 'CREATE_ACCOUNT_ERROR',
}

const SIGNIN = {
    LOGIN_ACCOUNT: 'LOGIN_ACCOUNT',
    LOGIN_ACCOUNT_SUCCESS: 'LOGIN_ACCOUNT_SUCCESS',
    LOGIN_ACCOUNT_ERROR: 'LOGIN_ACCOUNT_ERROR'
}

export {
    SIGNUP,
    SIGNIN
};
